version: '3.9'

services:
    chat-be:
      build:
        context: ./chat-be/
      ports:
        - "8000:8000"
      command: >
        sh -c "python3 manage.py migrate &&
               python3 manage.py runserver 0.0.0.0:8000"
      env_file: .env
      environment:
        - DB_HOST=$DB_HOST
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_PASS=$DB_PASS
        - REDIS_HOST=redis
      depends_on:
        - db
        - redis
                       
    db:
      image: postgres:13
      ports:
        - "5433:5432"
      env_file: .env
      environment:
        - POSTGRES_DB=$DB_NAME
        - POSTGRES_USER=$DB_USER
        - POSTGRES_PASSWORD=$DB_PASS

    redis:
      image: redis:alpine
      ports:
        - "6379:6379"

    chat-ui:
        build:
            context: ./chat-ui/
        ports:
            - "8080:80"

            