# Generated by Django 3.2.9 on 2021-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheduledmessage',
            name='date',
            field=models.DateTimeField(verbose_name='The date of the scheduled message'),
        ),
    ]
